=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/schemas/Actions.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:include schemaLocation="Types.xsd" />
<xs:include schemaLocation="Conditions.xsd" />

<xs:element name="DomainActions">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Action" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
        	<xs:sequence>
        		<xs:element name="PreConditions" minOccurs="0" maxOccurs="1">
        		    <xs:complexType>
        		    	<xs:choice minOccurs="0" maxOccurs="unbounded">
        					<xs:element name="Property" type="PropertyCondition" />
        					<xs:element name="RecentEvent" type="EventCondition"/>
        					<xs:element name="NewEvent" type="EventCondition"/>
        					<xs:element name="PastEvent" type="EventCondition"/>
        					<xs:element name="EmotionCondition" type="EmotionCondition"/>
        					<xs:element name="MoodCondition" type="MoodCondition"/>
        					<xs:element name="SACondition" type="SACondition"/>
        					<xs:element name="SAKnown" type="SAKnown"/>
        					<xs:element name="Predicate" type="PredicateCondition" />        					
        				</xs:choice>
         			</xs:complexType>
        		</xs:element>
    		    <xs:element name="Effects" minOccurs="0" maxOccurs="1">
        		    <xs:complexType>
        		    	<xs:sequence>
        		    		<xs:element name="Effect" type="Effect" minOccurs="0" maxOccurs="unbounded" />
        		    	</xs:sequence>    
         			</xs:complexType>
        		</xs:element>
        		<xs:element name="EffectsOnDrives" minOccurs="0" maxOccurs="1">
        		    <xs:complexType>
        		    	<xs:sequence>
        		    		<xs:element name="Motivator" minOccurs="0" maxOccurs="unbounded">
    					  		<xs:complexType>
    					  			<xs:attribute name="drive" type="externalMotivatorsType" use="required"/>
    					  			<xs:attribute name="target" type="xs:string" use="required"/>
    					  			<xs:attribute name="value" type="xs:string" use="required"/>
        		    			</xs:complexType>
        		    		</xs:element>
        		    	</xs:sequence>
        			</xs:complexType>
        		</xs:element>
        	</xs:sequence>
      		<xs:attribute name="name" type="xs:string" use="required"/>
      		<xs:attribute name="probability" type="xs:double" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="Effect">
	<xs:sequence>
		<xs:element name="Property" type="PropertyCondition" minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
    <xs:attribute name="probability" type="xs:double" use="required"/>
</xs:complexType>


</xs:schema>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/TestActions.xml
<DomainActions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/Actions.xsd">

	<Action name="TestAction([target])">
		<PreConditions>
		</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
		</EffectsOnDrives>
	</Action>

	<Action name="TestAction2">
		<PreConditions>
		</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
		</EffectsOnDrives>
	</Action>



</DomainActions>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/Actions-old.xml
<DomainActions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/Actions.xsd">
	
	<Action name="talk([target])">
		<PreConditions>																																							
		</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>
	
	<Action name="Chikaka()">
		<PreConditions>
		</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-0.5"/>
			<Motivator drive="Affiliation" target="[AGENT]" value="+1"/>
		</EffectsOnDrives>
	</Action>
	
	<Action name="bow([target])">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
     		</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>

  <Action name="walk-to-party()">
    <PreConditions>
    </PreConditions>
    <Effects>
    </Effects>
    <EffectsOnDrives>
      <Motivator drive="Energy" target="[AGENT]" value="-1"/>
    </EffectsOnDrives>
  </Action>
	
	<Action name="wave-hand([target])">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
     	</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>
	
	<Action name="thumb-up([target])">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
     	</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>
	
	<Action name="give-object([target])">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
     	</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>
	
	<Action name="spit-standing([target])">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
     	</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>
	
	<Action name="greeting([target])">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
     	</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>
	
	<!-- General SpeechAct -->
	<Action name="SpeechAct([target],[type])">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
			<Property name="[type]" operator="!=" value="protest"/>
			<Property name="[type]" operator="!=" value="deceptionreveal"/>
			<Property name="[type]" operator="!=" value="annoy"/>
			<Property name="[type]" operator="!=" value="laughoff"/>
			<Property name="[type]" operator="!=" value="followdontcare"/>
		</PreConditions>
		<Effects>
			<Effect probability="1">
				<Property name="SpeechContext()" operator="=" value="#EVENT([AGENT],SpeechAct,[target],[type])"/>
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>
	
	<!-- General SpeechAct that contains an additional topic -->
	<Action name="SpeechAct([target],[type],[topic])">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
			<Property name="[type]" operator="!=" value="joingroupquestionthreatleave"/>
			<Property name="[type]" operator="!=" value="joingroupquestionthreatleavepositiveanswer"/>
			<Property name="[type]" operator="!=" value="joingroupquestionthreatleavenegativeanswer"/>
			<Property name="[type]" operator="!=" value="joingroupquestionnegativeanswerobjectaccept"/>
			<Property name="[type]" operator="!=" value="joingroupquestionnegativeanswerobjectacceptanswer"/>
		</PreConditions>
		<Effects>
			<Effect probability="1">
				<Property name="SpeechContext()" operator="=" value="#EVENT([AGENT],SpeechAct,[target],[type],[topic])"/>
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>
	<!-- General Reinforcement SpeechAct -->
	<Action name="Reinforce([target],[type])">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
		</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
		</EffectsOnDrives>
	</Action>
	<!-- General Question SpeechAct -->
	<Action name="Question([target],[question])">
		<PreConditions>
			<Property name="[question]" operator="!=" value="threatfightback"/>
			<Property name="[question]" operator="!=" value="laughoff"/>
			<Property name="[question]" operator="!=" value="protest"/>
			<Property name="[question]" operator="!=" value="askforadvice"/>
			<Property name="[question]" operator="!=" value="askforadvice2nd"/>
			<Property name="[question]" operator="!=" value="askagain"/>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
		</PreConditions>
		<Effects>
			<Effect probability="1">
				<Property name="SpeechContext()" operator="=" value="#EVENT([AGENT],Question,[target],[question])"/>
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>
	<!-- General positive Reply SpeechAct. It's probability of execution by another agent is a little higher because this Reply is incentivated
	      by a question -->
	<Action name="Reply([target],[question],positiveanswer)" probability="0.5">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
			<Property name="[question]" operator="!=" value="joingroupquestionnegativeanswerobject"/>
			<Property name="SpeechContext()" operator="=" value="#EVENT([target],Question,[AGENT],[question])"/>
		</PreConditions>
		<Effects>
			<Effect probability="1">
				<Property name="SpeechContext()" operator="=" value="#EVENT([AGENT],Reply,[target],[question],positiveanswer)"/>
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>
	<!-- General negative Reply SpeechAct. It's probability of execution by another agent is a little higher because this Reply is incentivated
	      by a question. Additionally, saying no has some likelihood of getting hurt. -->
	<Action name="Reply([target],[question],negativeanswer)" probability="0.5">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
			<Property name="[question]" operator="!=" value="joinparty"/>
			<Property name="SpeechContext()" operator="=" value="#EVENT([target],Question,[AGENT],[question])"/>
		</PreConditions>
		<Effects>
			<Effect probability="0.4">
				<Property name="[AGENT](atRisk)" operator="=" value="True"/>
			</Effect>
			<Effect probability="1">
				<Property name="SpeechContext()" operator="=" value="#EVENT([AGENT],Reply,[target],[question],positiveanswer)"/>
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" target="[AGENT]" value="-1"/>
		</EffectsOnDrives>
	</Action>
</DomainActions>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/Actions-TeamBuddy.xml
<DomainActions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/Actions.xsd">

	<Action name="Spact([target],greet)">
		<PreConditions>
			<Property name="[target](isPerson)" operator="=" value="True" />	
			<Property name="[AGENT](near,[target])" operator="=" value="True" />
		</PreConditions>
		<Effects>
			<Effect probability="1">
				<Property name="SContext()" operator="=" value="#EVENT([AGENT],Spact,[target],greet)"/>
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" value="-0.5" target="[AGENT]"/>
			<Motivator drive="Affiliation" value="+3" target="[AGENT]"/>
			<Motivator drive="Affiliation" value="+3" target="[target]"/>
		</EffectsOnDrives>
	</Action>
	

	<Action name="Spact([target],handOverPhone)">
		<PreConditions>
			<Property name="[target](isPerson)" operator="=" value="True" />
			<Property name="[AGENT](near,[target])" operator="=" value="True" />
			<Property name="Phone(isRinging)" operator="=" value="True" />
			<Property name="Phone(onRobot)" operator="=" value="True" />
		</PreConditions>
		<Effects>
			<Effect probability="1">
				<Property name="SContext()" operator="=" value="#EVENT([AGENT],Spact,[target],handOverPhone)"/>
			</Effect>
			<Effect probability="0.6">
				<Property name="Phone(onRobot)" operator="=" value="False"/>
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" value="-0.5" target="[AGENT]"/>
		</EffectsOnDrives>
	</Action>
	
	<Action name="Spact([target],remind,[reminder])">
		<PreConditions>
			<Property name="[reminder](isReminder)" operator="=" value="True" />
			<Property name="[AGENT](near,[target])" operator="=" value="True" />
			<Property name="[target](isPerson)" operator="=" value="True" />
			<Property name="[reminder](for,[target])" operator="=" value="True" />
		</PreConditions>
		<Effects>
			<Effect probability="1">
				<Property name="SContext()" operator="=" value="#EVENT([AGENT],Spact,[target],remind,[reminder])"/>
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" value="-0.5" target="[AGENT]"/>
			<Motivator drive="Affiliation" value="+1" target="[AGENT]"/>
			<Motivator drive="Affiliation" value="+1" target="[target]"/>
		</EffectsOnDrives>
	</Action>

	<Action name="MoveToPerson([target])">
		<PreConditions>
			<Property name="[target](isPerson)" operator="=" value="True" />	
		</PreConditions>
		<Effects>
			<Effect probability="0.8">
				<Property name="[AGENT](near,[target])" operator="=" value="True" />
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" value="-0.5" target="[AGENT]"/>
		</EffectsOnDrives>	
	</Action>

	<Action name="MoveToPlace([place])">
		<PreConditions>
			<Property name="[place](isPlace)" operator="=" value="True" />	
		</PreConditions>
		<Effects>
			<Effect probability="1">
				<Property name="[AGENT](at,[place])" operator="=" value="True" />
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" value="-0.5" target="[AGENT]"/>
		</EffectsOnDrives>	
	</Action>
	
	<Action name="Charge([place])">
		<PreConditions>
			<Property name="[place](isChargingStation)" operator="=" value="True" />
			<Property name="[AGENT](at,[place])" operator="=" value="True" />
		</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Energy" value="+9" target="[AGENT]"/>
			<Motivator drive="Affiliation" value="-5" target="[AGENT]"/>
		</EffectsOnDrives>	
	</Action>
	
	<Action name="Migrate([platform])">
		<PreConditions>
			<Property name="[platform](isMigrationTarget)" operator="=" value="True" />
		</PreConditions>
		<Effects>
		</Effects>
		<EffectsOnDrives>
		</EffectsOnDrives>	
	</Action>


</DomainActions>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/LIRECYr2Actions.xml
<DomainActions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/Actions.xsd">

	<!--Action name="SpeechAct([target],replyLocation,[agent2],[location])">
		<PreConditions>
			<RecentEvent occurred="True" subject="[target]" action="AskLocation" target="[AGENT]" parameters="[agent2]"/>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
			<Property name="[agent2](location)" operator="=" value="[location]" />
		</PreConditions>
		<Effects>
			<Effect probability="1.0">
				<Property name="SpeechContext()" operator="=" value="#EVENT([AGENT],SpeechAct,[target],replyLocation,[location])"/>
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Affiliation" target="[AGENT]" value="+4"/>
			<Motivator drive="Affiliation" target="[target]" value="+2"/>
		</EffectsOnDrives>
	</Action-->
	
	
	<Action name="SpeechAct([target],replyLocation,[agent2],[possibleLocation])">
		<PreConditions>
			<RecentEvent occurred="True" subject="[target]" action="AskLocation" target="[AGENT]" parameters="[agent2]"/>
			<Property name="[target]" operator="!=" value="[AGENT]"/>
			<Property name="[AGENT](time)" operator="=" value="[time]"/>
			<Property name="[agent2](knowPossibleLocation,[time])" operator="=" value="True"/>
			<Property name="[agent2](possibleLocation,[time])" operator="=" value="[possibleLocation]"/>
		</PreConditions>
		<Effects>
			<Effect probability="1.0">
				<Property name="SpeechContext()" operator="=" value="#EVENT([AGENT],SpeechAct,[target],replyLocation,[possibleLocation])"/>
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Affiliation" target="[AGENT]" value="+4"/>
			<Motivator drive="Affiliation" target="[target]" value="+2"/>
		</EffectsOnDrives>
	</Action>
	
	<Action name="AskLocation([target],[agent2])">
		<PreConditions>
			<Property name="[target]" operator="!=" value="[AGENT]" />
		</PreConditions>
		<Effects>
			<Effect probability="1.0">
			</Effect>
		</Effects>
		<EffectsOnDrives>
		
		</EffectsOnDrives>
	</Action>		

	<Action name="SA([target],location)">
		<PreConditions>
			<Property name="[AGENT](time)" operator="=" value="[time]" />
			<Property name="[target](knowPossibleLocation,[time])" operator="!=" value="True" />
			<SACondition query="location" value="[possibleLocation]"/>
			<SAKnown name="target" value="[target]" />
			<SAKnown name="time" value="[time]"/>
		</PreConditions>
		<Effects>
			<Effect probability="1.0">
				<Property name="[target](possibleLocation,[time])" operator="=" value="[possibleLocation]" />
				<Property name="[target](knowPossibleLocation,[time])" operator="=" value="True" />
			</Effect>
		</Effects>
		<EffectsOnDrives>
			<Motivator drive="Affiliation" target="[AGENT]" value="+4"/>
			<Motivator drive="Affiliation" target="[target]" value="+2"/>
		</EffectsOnDrives>
	</Action>
	
</DomainActions>
