=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/schemas/Character.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:include schemaLocation="Types.xsd" />
<xs:include schemaLocation="Conditions.xsd" />

<xs:element name="Character">
  <xs:complexType>
    <xs:all>
		<xs:element name="EmotionalThresholds" type="EmotionalThresholds" minOccurs="1" maxOccurs="1"/>
   		<xs:element name="MotivationalParameters" type="MotivationalParameters" minOccurs="1" maxOccurs="1"/>
   		<xs:element name="Goals" type="Goals" minOccurs="1" maxOccurs="1"/>
   		<xs:element name="InterpersonalRelations" type="InterpersonalRelations" minOccurs="0" maxOccurs="1"/>
   		<xs:element name="EventReactions" type="EventReactions" minOccurs="0" maxOccurs="1"/>
   		<xs:element name="ActionTendencies" type="ActionTendencies" minOccurs="0" maxOccurs="1"/>
	</xs:all>
	<xs:attribute name="role" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>

<xs:complexType name="EmotionalThresholds">
    <xs:sequence>
    	<xs:element name="EmotionalThreshold" minOccurs="0" maxOccurs="22">
  			<xs:complexType>
  				<xs:attribute name="emotion" type="emotionType" use="required"/>
 				<xs:attribute name="threshold" type="xs:unsignedInt" use ="required" />
				<xs:attribute name="decay" type="xs:unsignedInt" use="required"/>
  			</xs:complexType>
  		</xs:element>
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="MotivationalParameters">
    <xs:sequence>
    	<xs:element name="MotivationalParameter" minOccurs="0" maxOccurs="unbounded">
  			<xs:complexType>
  				<xs:attribute name="motivator" type="allMotivatorsType" use="required"/>
				<xs:attribute name="decayFactor" type="xs:double" use="required"/>
 				<xs:attribute name="weight" type="xs:double" use ="required" />
 				<xs:attribute name="intensity" type="xs:double" use ="required" />
  			</xs:complexType>
  		</xs:element>
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="Goals">
    <xs:sequence>
    	<xs:element name="Goal" minOccurs="0" maxOccurs="unbounded">
  			<xs:complexType>
				<xs:attribute name="name" type="xs:string" use="required"/>
 				<xs:attribute name="importanceOfSuccess" type="xs:unsignedInt" use ="required" />
 				<xs:attribute name="importanceOfFailure" type="xs:unsignedInt" use ="required" />
  			</xs:complexType>
  		</xs:element>
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="InterpersonalRelations">
    <xs:sequence>
    	<xs:element name="Relation" minOccurs="0" maxOccurs="unbounded">
  			<xs:complexType>
				<xs:attribute name="target" type="xs:string" use="required"/>
 				<xs:attribute name="like" type="xs:integer" use ="optional" />
 				<xs:attribute name="respect" type="xs:integer" use ="optional" />
  			</xs:complexType>
  		</xs:element>
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="EventReactions">
    <xs:sequence>
    	<xs:element name="EmotionalReaction" minOccurs="0" maxOccurs="unbounded" type="EmotionalReaction" />
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="EmotionalReaction">
    <xs:sequence>
    	<xs:element name="Event" minOccurs="1" maxOccurs="1">
    		<xs:complexType>
  				<xs:attribute name="subject" type="xs:string" use ="optional" />
  				<xs:attribute name="action" type="xs:string" use="optional"/>
  				<xs:attribute name="target" type="xs:string" use="optional"/>
  				<xs:attribute name="parameters" type="xs:string" use="optional"/>
			</xs:complexType>
    	</xs:element>
   	</xs:sequence>
  	<xs:attribute name="desirability" type="xs:integer" use="optional"/>
  	<xs:attribute name="desirabilityForOther" type="xs:integer" use="optional"/>
  	<xs:attribute name="praiseworthiness" type="xs:integer" use="optional"/>
  	<xs:attribute name="other" type="xs:string" use="optional"/>
</xs:complexType>


<xs:complexType name="ActionTendencies">
    <xs:sequence>
    	<xs:element name="ActionTendency" minOccurs="0" maxOccurs="unbounded" type="ActionTendency" />
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="ActionTendency">
    <xs:sequence>
    	<xs:element name="Preconditions" minOccurs="1" maxOccurs="1">
    	   <xs:complexType>
        		    	<xs:choice minOccurs="0" maxOccurs="unbounded">
        					<xs:element name="Property" type="PropertyCondition" />
        					<xs:element name="RecentEvent" type="EventCondition"/>
        					<xs:element name="NewEvent" type="EventCondition"/>
        					<xs:element name="PastEvent" type="EventCondition"/>
        					<xs:element name="EmotionCondition" type="EmotionCondition"/>
        					<xs:element name="MoodCondition" type="MoodCondition"/>
        					<xs:element name="Predicate" type="PredicateCondition" />        					
        				</xs:choice>
         	</xs:complexType>
    	</xs:element>
    	<xs:element name="ElicitingEmotion" minOccurs="1" maxOccurs="1">
    		<xs:complexType>
    			<xs:sequence>
    				<xs:element name="CauseEvent" minOccurs="0" maxOccurs="1">
    					<xs:complexType>
  							<xs:attribute name="subject" type="xs:string" use ="optional" />
  							<xs:attribute name="action" type="xs:string" use="optional"/>
  							<xs:attribute name="target" type="xs:string" use="optional"/>
  							<xs:attribute name="parameters" type="xs:string" use="optional"/>
						</xs:complexType>
    				</xs:element>
    			</xs:sequence>
    			<xs:attribute name="type" type="emotionType" use="required"/>
    			<xs:attribute name="minIntensity" type="xs:unsignedInt" use="required"/>
    		</xs:complexType>
    	</xs:element>
  	</xs:sequence>
  	<xs:attribute name="action" type="xs:string" use="required"/>
</xs:complexType>



</xs:schema>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/roles/Blank/Blank.xml
<Character role="Blank" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../schemas/Character.xsd">
	<EmotionalThresholds>
		<EmotionalThreshold emotion="Love" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Hate" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Hope" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Fear" threshold="5" decay="8"/>
		<EmotionalThreshold emotion="Satisfaction" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Relief" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Fears-Confirmed" threshold="5" decay="8"/>
		<EmotionalThreshold emotion="Disappointment" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Joy" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Distress" threshold="3" decay="2"/>
		<EmotionalThreshold emotion="Happy-For" threshold="5" decay="8"/>
		<EmotionalThreshold emotion="Pitty" threshold="5" decay="8"/>
		<EmotionalThreshold emotion="Resentment" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Gloating" threshold="1" decay="8"/>
		<EmotionalThreshold emotion="Pride" threshold="2" decay="6"/>
		<EmotionalThreshold emotion="Shame" threshold="2" decay="6"/>
		<EmotionalThreshold emotion="Gratification" threshold="2" decay="6"/>
		<EmotionalThreshold emotion="Remorse" threshold="5" decay="8"/>
		<EmotionalThreshold emotion="Admiration" threshold="2" decay="6"/>
		<EmotionalThreshold emotion="Reproach" threshold="2" decay="6"/>
		<EmotionalThreshold emotion="Gratitude" threshold="2" decay="6"/>
		<EmotionalThreshold emotion="Anger" threshold="3" decay="8"/>
	</EmotionalThresholds>
	
	<MotivationalParameters>
		<MotivationalParameter motivator="Affiliation" decayFactor="1" weight="0.5" intensity="2"/>
		<MotivationalParameter motivator="Integrity" decayFactor="1" weight="0.5" intensity="6"/>
		<MotivationalParameter motivator="Energy" decayFactor="1" weight="0.5" intensity="5"/>
		<MotivationalParameter motivator="Certainty" decayFactor="0.2" weight="0.5" intensity="10"/>
		<MotivationalParameter motivator="Competence" decayFactor="0.2" weight="0.5" intensity="10"/>
	</MotivationalParameters>
		
	<Goals>
	</Goals>
	
	<InterpersonalRelations>
	</InterpersonalRelations>

	<ActionTendencies>
		<ActionTendency action="SpeechAct([Subject],generic-express-admiration)">
		<Preconditions>
            </Preconditions>
		<ElicitingEmotion type="Admiration" minIntensity="3">
			<CauseEvent subject="*" action="*" target="*"/>
		</ElicitingEmotion>
		</ActionTendency>
	</ActionTendencies>

	<EventReactions>
	</EventReactions>
</Character>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/roles/Cerkith/Cerkith.xml
<Character role="Cerkith" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../schemas/Character.xsd">
	<EmotionalThresholds>
		<EmotionalThreshold emotion="Love" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Hate" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Hope" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Fear" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Satisfaction" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Relief" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Fears-Confirmed" threshold="4" decay="8"/>
		<EmotionalThreshold emotion="Disappointment" threshold="3" decay="2"/>
		<EmotionalThreshold emotion="Joy" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Distress" threshold="3" decay="2"/>
		<EmotionalThreshold emotion="Happy-For" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Pitty" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Resentment" threshold="3" decay="2"/>
		<EmotionalThreshold emotion="Gloating" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Pride" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Shame" threshold="3" decay="2"/>
		<EmotionalThreshold emotion="Gratification" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Remorse" threshold="5" decay="8"/>
		<EmotionalThreshold emotion="Admiration" threshold="5" decay="8"/>
		<EmotionalThreshold emotion="Reproach" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Gratitude" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Anger" threshold="2" decay="8"/>
	</EmotionalThresholds>
	
	<MotivationalParameters>
		<MotivationalParameter motivator="Affiliation" decayFactor="10" weight="0.413" intensity="8"/>
		<MotivationalParameter motivator="Integrity" decayFactor="1" weight="0.67" intensity="4"/>
		<MotivationalParameter motivator="Energy" decayFactor="1" weight="0.3" intensity="5"/>
		<MotivationalParameter motivator="Certainty" decayFactor="2.5" weight="0.265" intensity="9"/>
		<MotivationalParameter motivator="Competence" decayFactor="1" weight="0.7" intensity="5"/>
	</MotivationalParameters>

	<Goals>
		<Goal name="Invite([target],[activity])" importanceOfSuccess="4" importanceOfFailure="3"/>
		<Goal name="ExplainRecyclingMachine([target],[machine],[button1],[button2])" importanceOfSuccess="4" importanceOfFailure="3"/>	
		<Goal name="AskToProduceLiquid([target],[body],[button])" importanceOfSuccess="4" importanceOfFailure="3"/>	
		<Goal name="DrinkWith([target],[liquid])" importanceOfSuccess="4" importanceOfFailure="3"/>	
	</Goals>
	
	<InterpersonalRelations>
		<Relation target="user" like="2" respect="1"/>
		<Relation target="Abbuk" like="2" respect="5"/>
		<Relation target="Evui" like="1" respect="-4"/>
		<Relation target="Errep" like="1" respect="-2"/>
		<Relation target="Ardoot" like="-2" respect="-4"/>
		<Relation target="Tigrit" like="3" respect="2"/>
		<Relation target="Ikop" like="-2" respect="-4"/>
	</InterpersonalRelations>
	
	<ActionTendencies>		
		<ActionTendency action="AngryGesture()">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Reproach" minIntensity="2">
				<CauseEvent subject="*" action="GreetWrongly" target="[SELF]" />
			</ElicitingEmotion>
        </ActionTendency>
		
		<ActionTendency action="AngryGesture()">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Reproach" minIntensity="2">
				<CauseEvent subject="*" action="RejectInvitation" target="[SELF]" />
			</ElicitingEmotion>
        </ActionTendency>
		
		<ActionTendency action="AngryGesture()">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Reproach" minIntensity="2">
				<CauseEvent subject="*" action="RejectOffer" target="[SELF]" />
			</ElicitingEmotion>
        </ActionTendency>
		
		<ActionTendency action="SpeechAct([Subject],warn,[Target])">
            <Preconditions>
				<Property name="recycling(isActivity)" operator="=" value="True"/>
            </Preconditions>
            <ElicitingEmotion type="Reproach" minIntensity="1">
				<CauseEvent subject="*" action="ApproachMachine" target="*"/>
			</ElicitingEmotion>
        </ActionTendency>
		
		<ActionTendency action="SpeechAct([Subject],angryMachineBroke)">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Reproach" minIntensity="2">
				<CauseEvent subject="*" action="PressWrongButton" target="*" />
			</ElicitingEmotion>
        </ActionTendency>
		
		<ActionTendency action="AngryGesture()">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Reproach" minIntensity="2">
				<CauseEvent subject="*" action="PressWrongButton" target="*" />
			</ElicitingEmotion>
        </ActionTendency>
        
         <ActionTendency action="SpeechAct([Subject],midStatusReply)">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Admiration" minIntensity="0">
				<CauseEvent subject="*" action="AskQuestion" target="[SELF]" />
			</ElicitingEmotion>
        </ActionTendency>

        <!-- Dinner party scenario -->
        <ActionTendency action="SpeechAct([Subject],generic-express-admiration)">
			<Preconditions>
            </Preconditions>
			<ElicitingEmotion type="Admiration" minIntensity="3">
				<CauseEvent subject="*" action="*" target="*"/>
			</ElicitingEmotion>
		</ActionTendency>
	</ActionTendencies>	
	
</Character>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/roles/ABRobot/ABRobot.xml
<Character role="ABRobot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../schemas/Character.xsd">

	<EmotionalThresholds>
		<EmotionalThreshold emotion="Love" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Hate" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Hope" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Fear" threshold="4" decay="8"/>
		<EmotionalThreshold emotion="Satisfaction" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Relief" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Fears-Confirmed" threshold="4" decay="8"/>
		<EmotionalThreshold emotion="Disappointment" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Joy" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Distress" threshold="3" decay="2"/>
		<EmotionalThreshold emotion="Happy-For" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Pitty" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Resentment" threshold="5" decay="2"/>
		<EmotionalThreshold emotion="Gloating" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Pride" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Shame" threshold="5" decay="2"/>
		<EmotionalThreshold emotion="Gratification" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Remorse" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Admiration" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Reproach" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Gratitude" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Anger" threshold="3" decay="8"/>
	</EmotionalThresholds>
	
	<MotivationalParameters>
		<MotivationalParameter motivator="Affiliation" decayFactor="12.5" weight="0.4" intensity="7"/>
		<MotivationalParameter motivator="Integrity" decayFactor="0.5" weight="0.7" intensity="3"/>
		<MotivationalParameter motivator="Energy" decayFactor="2" weight="0.2" intensity="6"/>
		<MotivationalParameter motivator="Certainty" decayFactor="1.5" weight="0.25" intensity="5"/>
		<MotivationalParameter motivator="Competence" decayFactor="1.5" weight="0.775" intensity="6"/>
	</MotivationalParameters>

	<Goals>
		<Goal name="respondYes([target],[person],[task],[item])" importanceOfSuccess="8" importanceOfFailure="8"/>
		<Goal name="respondNo([target],[person],[task],[item])" importanceOfSuccess="8" importanceOfFailure="8"/>
	</Goals>
	
	<InterpersonalRelations>
		<Relation target="Amy" like="3" respect="1"/>
		<Relation target="John" like="3" respect="1"/>
	</InterpersonalRelations>
	
	<!--
	This event reaction is needed in order to keep the event in memory. Otherwise it is not moved to LTM.	
	-->
	<EventReactions>
         <EmotionalReaction desirability="4" desirabilityForOther="0" praiseworthiness="0">
            <Event subject="Amy" action="read" />
        </EmotionalReaction>
	</EventReactions>
	
</Character>
