=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/schemas/Character.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:include schemaLocation="Types.xsd" />
<xs:include schemaLocation="Conditions.xsd" />

<xs:element name="Character">
  <xs:complexType>
    <xs:all>
		<xs:element name="EmotionalThresholds" type="EmotionalThresholds" minOccurs="1" maxOccurs="1"/>
   		<xs:element name="MotivationalParameters" type="MotivationalParameters" minOccurs="1" maxOccurs="1"/>
   		<xs:element name="Goals" type="Goals" minOccurs="1" maxOccurs="1"/>
   		<xs:element name="InterpersonalRelations" type="InterpersonalRelations" minOccurs="0" maxOccurs="1"/>
   		<xs:element name="EventReactions" type="EventReactions" minOccurs="0" maxOccurs="1"/>
   		<xs:element name="ActionTendencies" type="ActionTendencies" minOccurs="0" maxOccurs="1"/>
	</xs:all>
	<xs:attribute name="role" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>

<xs:complexType name="EmotionalThresholds">
    <xs:sequence>
    	<xs:element name="EmotionalThreshold" minOccurs="0" maxOccurs="22">
  			<xs:complexType>
  				<xs:attribute name="emotion" type="emotionType" use="required"/>
 				<xs:attribute name="threshold" type="xs:unsignedInt" use ="required" />
				<xs:attribute name="decay" type="xs:unsignedInt" use="required"/>
  			</xs:complexType>
  		</xs:element>
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="MotivationalParameters">
    <xs:sequence>
    	<xs:element name="MotivationalParameter" minOccurs="0" maxOccurs="unbounded">
  			<xs:complexType>
  				<xs:attribute name="motivator" type="allMotivatorsType" use="required"/>
				<xs:attribute name="decayFactor" type="xs:double" use="required"/>
 				<xs:attribute name="weight" type="xs:double" use ="required" />
 				<xs:attribute name="intensity" type="xs:double" use ="required" />
  			</xs:complexType>
  		</xs:element>
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="Goals">
    <xs:sequence>
    	<xs:element name="Goal" minOccurs="0" maxOccurs="unbounded">
  			<xs:complexType>
				<xs:attribute name="name" type="xs:string" use="required"/>
 				<xs:attribute name="importanceOfSuccess" type="xs:unsignedInt" use ="required" />
 				<xs:attribute name="importanceOfFailure" type="xs:unsignedInt" use ="required" />
  			</xs:complexType>
  		</xs:element>
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="InterpersonalRelations">
    <xs:sequence>
    	<xs:element name="Relation" minOccurs="0" maxOccurs="unbounded">
  			<xs:complexType>
				<xs:attribute name="target" type="xs:string" use="required"/>
 				<xs:attribute name="like" type="xs:integer" use ="optional" />
 				<xs:attribute name="respect" type="xs:integer" use ="optional" />
  			</xs:complexType>
  		</xs:element>
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="EventReactions">
    <xs:sequence>
    	<xs:element name="EmotionalReaction" minOccurs="0" maxOccurs="unbounded" type="EmotionalReaction" />
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="EmotionalReaction">
    <xs:sequence>
    	<xs:element name="Event" minOccurs="1" maxOccurs="1">
    		<xs:complexType>
  				<xs:attribute name="subject" type="xs:string" use ="optional" />
  				<xs:attribute name="action" type="xs:string" use="optional"/>
  				<xs:attribute name="target" type="xs:string" use="optional"/>
  				<xs:attribute name="parameters" type="xs:string" use="optional"/>
			</xs:complexType>
    	</xs:element>
   	</xs:sequence>
  	<xs:attribute name="desirability" type="xs:integer" use="optional"/>
  	<xs:attribute name="desirabilityForOther" type="xs:integer" use="optional"/>
  	<xs:attribute name="praiseworthiness" type="xs:integer" use="optional"/>
  	<xs:attribute name="other" type="xs:string" use="optional"/>
</xs:complexType>


<xs:complexType name="ActionTendencies">
    <xs:sequence>
    	<xs:element name="ActionTendency" minOccurs="0" maxOccurs="unbounded" type="ActionTendency" />
  	</xs:sequence>
</xs:complexType>

<xs:complexType name="ActionTendency">
    <xs:sequence>
    	<xs:element name="Preconditions" minOccurs="1" maxOccurs="1">
    	   <xs:complexType>
        		    	<xs:choice minOccurs="0" maxOccurs="unbounded">
        					<xs:element name="Property" type="PropertyCondition" />
        					<xs:element name="RecentEvent" type="EventCondition"/>
        					<xs:element name="NewEvent" type="EventCondition"/>
        					<xs:element name="PastEvent" type="EventCondition"/>
        					<xs:element name="EmotionCondition" type="EmotionCondition"/>
        					<xs:element name="MoodCondition" type="MoodCondition"/>
        					<xs:element name="Predicate" type="PredicateCondition" />        					
        				</xs:choice>
         	</xs:complexType>
    	</xs:element>
    	<xs:element name="ElicitingEmotion" minOccurs="1" maxOccurs="1">
    		<xs:complexType>
    			<xs:sequence>
    				<xs:element name="CauseEvent" minOccurs="0" maxOccurs="1">
    					<xs:complexType>
  							<xs:attribute name="subject" type="xs:string" use ="optional" />
  							<xs:attribute name="action" type="xs:string" use="optional"/>
  							<xs:attribute name="target" type="xs:string" use="optional"/>
  							<xs:attribute name="parameters" type="xs:string" use="optional"/>
						</xs:complexType>
    				</xs:element>
    			</xs:sequence>
    			<xs:attribute name="type" type="emotionType" use="required"/>
    			<xs:attribute name="minIntensity" type="xs:unsignedInt" use="required"/>
    		</xs:complexType>
    	</xs:element>
  	</xs:sequence>
  	<xs:attribute name="action" type="xs:string" use="required"/>
</xs:complexType>



</xs:schema>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/roles/Ardoot/Ardoot.xml
<Character role="Ardoot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../schemas/Character.xsd">
	<EmotionalThresholds>
		<EmotionalThreshold emotion="Love" threshold="4" decay="5"/>
		<EmotionalThreshold emotion="Hate" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Hope" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Fear" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Satisfaction" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Relief" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Fears-Confirmed" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Disappointment" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Joy" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Distress" threshold="3" decay="2"/>
		<EmotionalThreshold emotion="Happy-For" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Pitty" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Resentment" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Gloating" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Pride" threshold="1" decay="8"/>
		<EmotionalThreshold emotion="Shame" threshold="5" decay="2"/>
		<EmotionalThreshold emotion="Gratification" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Remorse" threshold="5" decay="8"/>
		<EmotionalThreshold emotion="Admiration" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Reproach" threshold="1" decay="8"/>
		<EmotionalThreshold emotion="Gratitude" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Anger" threshold="3" decay="8"/>
	</EmotionalThresholds>
	
	<MotivationalParameters>
		<MotivationalParameter motivator="Affiliation" decayFactor="10" weight="0.425" intensity="8"/>
		<MotivationalParameter motivator="Integrity" decayFactor="1" weight="0.76" intensity="5"/>
		<MotivationalParameter motivator="Energy" decayFactor="1" weight="0.7" intensity="6"/>
		<MotivationalParameter motivator="Certainty" decayFactor="1.5" weight="0.365" intensity="6"/>
		<MotivationalParameter motivator="Competence" decayFactor="1.5" weight="0.825" intensity="7"/>
	</MotivationalParameters>

	<Goals>
		<Goal name="ProvideKnowledge([target])" importanceOfSuccess="4" importanceOfFailure="3"/>	
		<Goal name="AskFor([target],[soil])" importanceOfSuccess="4" importanceOfFailure="3"/>
		<Goal name="ApproveFelling([target])" importanceOfSuccess="4" importanceOfFailure="3"/>	
	</Goals>
	
	<InterpersonalRelations>
		<Relation target="user" like="2" respect="1"/>
		<Relation target="Abbuk" like="2" respect="1"/>
		<Relation target="Evui" like="-1" respect="-5"/>
		<Relation target="Cerkith" like="-2" respect="-3"/>
		<Relation target="Errep" like="-1" respect="-3"/>
		<Relation target="Tigrit" like="-1" respect="4"/>
		<Relation target="Ikop" like="3" respect="1"/>
	</InterpersonalRelations>
	
	<ActionTendencies>	
		
		<ActionTendency action="AngryGesture()">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Reproach" minIntensity="2">
				<CauseEvent subject="*" action="GreetWrongly" target="[SELF]" />
			</ElicitingEmotion>
        </ActionTendency>
		
		<ActionTendency action="AngryGesture()">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Reproach" minIntensity="2">
				<CauseEvent subject="*" action="RejectInvitation" target="[SELF]" />
			</ElicitingEmotion>
        </ActionTendency>
		
		<ActionTendency action="AngryGesture()">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Reproach" minIntensity="2">
				<CauseEvent subject="*" action="RejectOffer" target="[SELF]" />
			</ElicitingEmotion>
        </ActionTendency>
					
		<ActionTendency action="SpeechAct([Subject],angryTreeDied)">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Reproach" minIntensity="2">
				<CauseEvent subject="*" action="StepOnTree" target="*" />
			</ElicitingEmotion>
        </ActionTendency>
		
		<ActionTendency action="AngryGesture()">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Reproach" minIntensity="2">
				<CauseEvent subject="*" action="StepOnTree" target="*" />
			</ElicitingEmotion>
        </ActionTendency>
        
        <ActionTendency action="SpeechAct([Subject],highStatusReply)">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Admiration" minIntensity="0">
				<CauseEvent subject="*" action="AskQuestion" target="[SELF]" />
			</ElicitingEmotion>
        </ActionTendency>

        <!-- Dinner party scenario -->
        <ActionTendency action="SpeechAct([Subject],generic-express-admiration)">
			<Preconditions>
            </Preconditions>
			<ElicitingEmotion type="Admiration" minIntensity="5">
				<CauseEvent subject="*" action="*" target="*"/>
			</ElicitingEmotion>
		</ActionTendency>
	</ActionTendencies>	
	
</Character>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/roles/Sarah/Sarah.xml
<Character role="Sarah" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../schemas/Character.xsd">
	<EmotionalThresholds>
		<EmotionalThreshold emotion="Love" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Hate" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Hope" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Fear" threshold="4" decay="8"/>
		<EmotionalThreshold emotion="Satisfaction" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Relief" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Fears-Confirmed" threshold="4" decay="8"/>
		<EmotionalThreshold emotion="Disappointment" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Joy" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Distress" threshold="3" decay="2"/>
		<EmotionalThreshold emotion="Happy-For" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Pitty" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Resentment" threshold="5" decay="2"/>
		<EmotionalThreshold emotion="Gloating" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Pride" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Shame" threshold="5" decay="2"/>
		<EmotionalThreshold emotion="Gratification" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Remorse" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Admiration" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Reproach" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Gratitude" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Anger" threshold="3" decay="8"/>
	</EmotionalThresholds>
	
	<MotivationalParameters>
		<MotivationalParameter motivator="Affiliation" decayFactor="12.5" weight="0.4" intensity="7"/>
		<MotivationalParameter motivator="Integrity" decayFactor="0.5" weight="0.7" intensity="3"/>
		<MotivationalParameter motivator="Energy" decayFactor="2" weight="0.2" intensity="6"/>
		<MotivationalParameter motivator="Certainty" decayFactor="1.5" weight="0.25" intensity="5"/>
		<MotivationalParameter motivator="Competence" decayFactor="1.5" weight="0.775" intensity="6"/>
	</MotivationalParameters>

	<Goals>
		<Goal name="Greet([target])" importanceOfSuccess="4" importanceOfFailure="3"/>
		<Goal name="Welcome([target])" importanceOfSuccess="4" importanceOfFailure="3"/>
		<Goal name="SwearSecrecy([target],[friend],[info])" importanceOfSuccess="4" importanceOfFailure="3"/>
		<Goal name="ReplyHideInfo([target],[friend],[info])" importanceOfSuccess="4" importanceOfFailure="3"/>
		<Goal name="DontTellInfo([target],[friend],[info])" importanceOfSuccess="4" importanceOfFailure="3"/>
		<Goal name="ReplyTellInfo([target],[friend],[info])" importanceOfSuccess="4" importanceOfFailure="3"/>
	</Goals>
	
	<InterpersonalRelations>
		<Relation target="John" like="2" respect="1"/>
		<Relation target="Luke" like="2" respect="1"/>
		<Relation target="Paulie" like="2" respect="1"/>
	</InterpersonalRelations>
</Character>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/roles/TeamBuddy/TeamBuddy.xml
<Character role="TeamBuddy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../schemas/Character.xsd">
	<EmotionalThresholds>
		<EmotionalThreshold emotion="Love" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Hate" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Hope" threshold="1" decay="8"/>
		<EmotionalThreshold emotion="Fear" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Satisfaction" threshold="1" decay="8"/>
		<EmotionalThreshold emotion="Relief" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Fears-Confirmed" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Disappointment" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Joy" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Distress" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Happy-For" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Pitty" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Resentment" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Gloating" threshold="1" decay="8"/>
		<EmotionalThreshold emotion="Pride" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Shame" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Gratification" threshold="1" decay="8"/>
		<EmotionalThreshold emotion="Remorse" threshold="1" decay="2"/>
		<EmotionalThreshold emotion="Admiration" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Reproach" threshold="1" decay="8"/>
		<EmotionalThreshold emotion="Gratitude" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Anger" threshold="1" decay="5"/>
	</EmotionalThresholds>
	
	<MotivationalParameters>
		<MotivationalParameter motivator="Affiliation" decayFactor="0.005" weight="0.5" intensity="6"/>
		<MotivationalParameter motivator="Integrity" decayFactor="0.005" weight="0.5" intensity="6"/>
		<MotivationalParameter motivator="Energy" decayFactor="0.005" weight="0.5" intensity="6"/>
		<MotivationalParameter motivator="Certainty" decayFactor="0.005" weight="0.5" intensity="6"/>
		<MotivationalParameter motivator="Competence" decayFactor="0.005" weight="0.5" intensity="6"/>
	</MotivationalParameters>
	
	<Goals>
		<Goal name="MorningGreeting([target])" importanceOfSuccess="8" importanceOfFailure="6"/>
		<Goal name="DeliverPhone([target])" importanceOfSuccess="8" importanceOfFailure="6"/>
		<Goal name="Remind([target],[reminder])" importanceOfSuccess="8" importanceOfFailure="6"/>
		<Goal name="ChargeAt([charger])" importanceOfSuccess="8" importanceOfFailure="6"/>
		<Goal name="Migration([platform])" importanceOfSuccess="8" importanceOfFailure="6"/>
	</Goals>
	
	<InterpersonalRelations>
	</InterpersonalRelations>
</Character>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/roles/TestAgent/TestAgent.xml
<Character role="Greta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../schemas/Character.xsd">
	<EmotionalThresholds>
		<EmotionalThreshold emotion="Love" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Hate" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Hope" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Fear" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Satisfaction" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Relief" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Fears-Confirmed" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Disappointment" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Joy" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Distress" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Happy-For" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Pitty" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Resentment" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Gloating" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Pride" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Shame" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Gratification" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Remorse" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Admiration" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Reproach" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Gratitude" threshold="0" decay="1"/>
		<EmotionalThreshold emotion="Anger" threshold="0" decay="1"/>
	</EmotionalThresholds>
	
	<MotivationalParameters>
			<MotivationalParameter motivator="Affiliation" decayFactor="1" weight="0.7" intensity="3"/>
			<MotivationalParameter motivator="Integrity" decayFactor="0.5" weight="0.7" intensity="3"/>
			<MotivationalParameter motivator="Energy" decayFactor="2" weight="0.2" intensity="6"/>
			<MotivationalParameter motivator="Certainty" decayFactor="1.5" weight="0.25" intensity="5"/>
			<MotivationalParameter motivator="Competence" decayFactor="1.5" weight="0.775" intensity="6"/>
	</MotivationalParameters>
	
	<Goals>
		
		<Goal name="GatherInformation([target])" importanceOfSuccess="7" importanceOfFailure="7"/>
		
		<!--
		<Goal name="Goal1([target])" importanceOfSuccess="8" importanceOfFailure="6"/>
		<Goal name="Goal2([target])" importanceOfSuccess="8" importanceOfFailure="6"/>
		<Goal name="InterestGoal1_test(test)_False" importanceOfSuccess="2" importanceOfFailure="2" />--> 
	</Goals>
	
	<InterpersonalRelations>
	</InterpersonalRelations>
	
	<EventReactions>
	    
		<EmotionalReaction desirability="6" desirabilityForOther="-4" praiseworthiness="-5">
            <Event subject="SELF" action="TestAction" target="*" />
        </EmotionalReaction>
	
	</EventReactions>
	
	<ActionTendencies>
		<!-- 
		<ActionTendency action="TestAction3()">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Joy" minIntensity="1">
				<CauseEvent />
			</ElicitingEmotion>
        </ActionTendency>
         -->
		<ActionTendency action="TestAction4()">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Fear" minIntensity="5">
				<CauseEvent />
			</ElicitingEmotion>
        </ActionTendency>
        
 
	</ActionTendencies>
</Character>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/roles/Evui/Evui.xml
<Character role="Evui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../schemas/Character.xsd">
	<EmotionalThresholds>
		<EmotionalThreshold emotion="Love" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Hate" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Hope" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Fear" threshold="1" decay="8"/>
		<EmotionalThreshold emotion="Satisfaction" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Relief" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Fears-Confirmed" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Disappointment" threshold="4" decay="2"/>
		<EmotionalThreshold emotion="Joy" threshold="1" decay="3"/>
		<EmotionalThreshold emotion="Distress" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Happy-For" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Pitty" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Resentment" threshold="5" decay="2"/>
		<EmotionalThreshold emotion="Gloating" threshold="5" decay="8"/>
		<EmotionalThreshold emotion="Pride" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Shame" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Gratification" threshold="1" decay="5"/>
		<EmotionalThreshold emotion="Remorse" threshold="5" decay="8"/>
		<EmotionalThreshold emotion="Admiration" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Reproach" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Gratitude" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Anger" threshold="3" decay="8"/>
	</EmotionalThresholds>
	
	<MotivationalParameters>
		<MotivationalParameter motivator="Affiliation" decayFactor="10" weight="0.6" intensity="8"/>
		<MotivationalParameter motivator="Integrity" decayFactor="0.5" weight="0.67" intensity="4"/>
		<MotivationalParameter motivator="Energy" decayFactor="1" weight="0.7" intensity="5"/>
		<MotivationalParameter motivator="Certainty" decayFactor="1" weight="0.25" intensity="5"/>
		<MotivationalParameter motivator="Competence" decayFactor="1.5" weight="0.65" intensity="7"/>
	</MotivationalParameters>

	<Goals>
		<Goal name="AttractAttention([target])" importanceOfSuccess="4" importanceOfFailure="3"/>
		<Goal name="DemonstratePickFromTree([target],[food])" importanceOfSuccess="4" importanceOfFailure="3"/>
		<Goal name="Apologise([target])" importanceOfSuccess="4" importanceOfFailure="3"/>
	</Goals>
	
	<InterpersonalRelations>
		<Relation target="user" like="3" respect="2"/>
		<Relation target="Abbuk" like="0" respect="5"/>
		<Relation target="Errep" like="2" respect="2"/>
		<Relation target="Cerkith" like="0" respect="3"/>
		<Relation target="Ardoot" like="0" respect="2"/>
		<Relation target="Tigrit" like="0" respect="2"/>
		<Relation target="Ikop" like="0" respect="2"/>
	</InterpersonalRelations>
	
	<ActionTendencies>	
	     <ActionTendency action="Surprise()">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Love" minIntensity="0">
				<CauseEvent subject="[SELF]" action="look-at" target="*" />
			</ElicitingEmotion>
        </ActionTendency>
        
        <ActionTendency action="SpeechAct([Subject],lowStatusReply)">
            <Preconditions>
            </Preconditions>
            <ElicitingEmotion type="Admiration" minIntensity="0">
				<CauseEvent subject="*" action="AskQuestion" target="[SELF]" />
			</ElicitingEmotion>
        </ActionTendency>
	</ActionTendencies>	
	
	 

</Character>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/roles/Jonas/Jonas.xml
<Character role="Jonas" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../../schemas/Character.xsd">
	
	<EmotionalThresholds>
		<EmotionalThreshold emotion="Love" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Hate" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Hope" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Fear" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Satisfaction" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Relief" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Fears-Confirmed" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Disappointment" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Joy" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Distress" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Happy-For" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Pitty" threshold="2" decay="2"/>
		<EmotionalThreshold emotion="Resentment" threshold="3" decay="2"/>
		<EmotionalThreshold emotion="Gloating" threshold="3" decay="8"/>
		<EmotionalThreshold emotion="Pride" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Shame" threshold="3" decay="2"/>
		<EmotionalThreshold emotion="Gratification" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Remorse" threshold="3" decay="2"/>
		<EmotionalThreshold emotion="Admiration" threshold="2" decay="5"/>
		<EmotionalThreshold emotion="Reproach" threshold="2" decay="8"/>
		<EmotionalThreshold emotion="Gratitude" threshold="3" decay="5"/>
		<EmotionalThreshold emotion="Anger" threshold="3" decay="5"/>
	</EmotionalThresholds>
	
	<MotivationalParameters>
		<MotivationalParameter motivator="Affiliation" decayFactor="2" weight="0.075" intensity="6"/>
		<MotivationalParameter motivator="Integrity" decayFactor="1.5" weight="0.05" intensity="4"/>
		<MotivationalParameter motivator="Energy" decayFactor="2" weight="0.055" intensity="5"/>
		<MotivationalParameter motivator="Certainty" decayFactor="4" weight="0.065" intensity="4"/>
		<MotivationalParameter motivator="Competence" decayFactor="3" weight="0.05" intensity="4"/>
	</MotivationalParameters>

	<Goals>
	</Goals>
	
	<InterpersonalRelations>
		
		<Relation target="Luke" like="1" respect="0"/>
		<Relation target="book" like="6"/>
		<Relation target="Paul" like="-1" respect="-1"/>
		<Relation target="Ollie" like="1" respect="1"/>
		<Relation target="Rob" like="2" respect="1"/>
		<Relation target="Janet" like="1" respect="-1"/>
		<Relation target="Sarah" like="0" />
		<Relation target="Nita" like="0" />
		<Relation target="Martina" like="2" respect="1"/>
		<Relation target="Elinor" like="4" respect="1"/>
	</InterpersonalRelations>
	
	<EventReactions>	
      
	</EventReactions>
	
	<ActionTendencies>
	
		
		<!-- Action tendency of insulting when the victim is angry. This also corresponds to the insult coping strategy. -->
		<ActionTendency action="SpeechAct([Subject],insult)">
			<Preconditions>
            		</Preconditions>
			<ElicitingEmotion type="Anger" minIntensity="4">
				<CauseEvent/>
			</ElicitingEmotion>
		</ActionTendency>
		
		<!-- Action tendency of crying when the -->
		<ActionTendency action="cry">
			<Preconditions>
            		</Preconditions>
			<ElicitingEmotion type="Distress" minIntensity="4">
				<CauseEvent/>
			</ElicitingEmotion>
		</ActionTendency>

		<ActionTendency action="frown">
			<Preconditions>
            		</Preconditions>
			<ElicitingEmotion type="Distress" minIntensity="2">
				<CauseEvent/>
			</ElicitingEmotion>
		</ActionTendency>

		<ActionTendency action="laugh">
			<Preconditions>
            		</Preconditions>
			<ElicitingEmotion type="Joy" minIntensity="4">
				<CauseEvent/>
			</ElicitingEmotion>
		</ActionTendency>

		<ActionTendency action="smile">
			<Preconditions>
            		</Preconditions>
			<ElicitingEmotion type="Joy" minIntensity="1">
				<CauseEvent/>
			</ElicitingEmotion>		
		</ActionTendency>		
		
				
	</ActionTendencies>
</Character>
