=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/schemas/GoalLibrary.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:include schemaLocation="Types.xsd" />
<xs:include schemaLocation="Conditions.xsd" />

<xs:element name="GoalLibrary">
  <xs:complexType>
    <xs:sequence>
    	<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="ActivePursuitGoal" type="ActivePursuitGoal" />
    		<xs:element name="InterestGoal" type="InterestGoal"/>
		</xs:choice>
	</xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="ActivePursuitGoal">
    <xs:sequence>
    	<xs:element name="PreConditions" minOccurs="0" maxOccurs="1">
            <xs:complexType>
            	<xs:choice minOccurs="0" maxOccurs="unbounded">
        			<xs:element name="Property" type="PropertyCondition" />
        			<xs:element name="Predicate" type="PredicateCondition" />
        			<xs:element name="RecentEvent" type="EventCondition"/>
        			<xs:element name="PastEvent" type="EventCondition"/>
        			<xs:element name="NewEvent" type="EventCondition"/>
        			<xs:element name="RitualCondition" type="RitualCondition"/>
        			<xs:element name="EmotionCondition" type="EmotionCondition"/>
        			<xs:element name="MoodCondition" type="EmotionCondition"/>
   				</xs:choice>
   			</xs:complexType>
   		</xs:element>	
    	<xs:element name="SucessConditions" minOccurs="0" maxOccurs="1">
            <xs:complexType>
            	<xs:choice minOccurs="0" maxOccurs="unbounded">
        			<xs:element name="Property" type="PropertyCondition" />
        			<xs:element name="Predicate" type="PredicateCondition" />
        			<xs:element name="RecentEvent" type="EventCondition"/>
        			<xs:element name="PastEvent" type="EventCondition"/>
        			<xs:element name="NewEvent" type="EventCondition"/>
        			<xs:element name="EmotionCondition" type="EmotionCondition"/>
        			<xs:element name="MoodCondition" type="MoodCondition"/>
   				</xs:choice>
   			</xs:complexType>
   		</xs:element>	
    	<xs:element name="FailureConditions" minOccurs="0" maxOccurs="1">
            <xs:complexType>
            	<xs:choice minOccurs="0" maxOccurs="unbounded">
        			<xs:element name="Property" type="PropertyCondition" />
        			<xs:element name="Predicate" type="PredicateCondition" />        			
        			<xs:element name="RecentEvent" type="EventCondition"/>
        			<xs:element name="PastEvent" type="EventCondition"/>
        			<xs:element name="NewEvent" type="EventCondition"/>
        			<xs:element name="EmotionCondition" type="EmotionCondition"/>
        			<xs:element name="MoodCondition" type="MoodCondition"/>      			
   				</xs:choice>
   			</xs:complexType>
   		</xs:element>
   		<xs:element name="ExpectedEffects" minOccurs="0" maxOccurs="1">
        		    <xs:complexType>
        		    	<xs:sequence>
					    	<xs:choice minOccurs="0" maxOccurs="unbounded">
								<xs:element name="OnSelect" type="ExpectedEffect" />
    							<xs:element name="OnIgnore" type="ExpectedEffect"/>
							</xs:choice>
        		    	</xs:sequence>
        			</xs:complexType>
        </xs:element>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="InterestGoal">
    <xs:sequence>
    	<xs:element name="ProtectionConstraints" minOccurs="1" maxOccurs="1">
    		<xs:complexType>
				<xs:sequence>
					<xs:element name="Property" type="PropertyCondition" minOccurs="1" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="ExpectedEffect">
 <xs:attribute name="drive" type="externalMotivatorsType" use="required"/>
 <xs:attribute name="target" type="xs:string" use="required"/>
 <xs:attribute name="value" type="xs:string" use="required"/>
</xs:complexType>

</xs:schema>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/SimpleGoalLibraryWithDrives.xml
<GoalLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/GoalLibrary.xsd">

    <ActivePursuitGoal name="Eat([target])">
		<PreConditions>
			<Property name="[target](eatable)" operator="=" value="True" />
			<Property name="SELF(has,[target])" operator="=" value="True" />
		</PreConditions>
		<SuccessConditions>
			<NewEvent occurred="True" subject="SELF" action="Eat" target="[target]" />
		</SuccessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Energy" target="[SELF]" value="+3"/>
		</ExpectedEffects>	
	</ActivePursuitGoal>
	
	<ActivePursuitGoal name="Rest()">
		<PreConditions>
		</PreConditions>
		<SuccessConditions>
			<NewEvent occurred="True" subject="SELF" action="Rests" />
		</SuccessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Integrity" target="[SELF]" value="+2"/>
		</ExpectedEffects>	
	</ActivePursuitGoal>
	
	<ActivePursuitGoal name="AcceptInvitation([target])">
		<PreConditions>
			<Property name="SELF(invitedBy,[target])" operator="=" value="True" />
			<LikeRelation subject="[SELF]" target="[target]" operator="GreaterThan" value="0" />
		</PreConditions>
		<SuccessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="acceptinvitation"/>
		</SuccessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Affiliation" target="SELF" value="+4"/>
		</ExpectedEffects>	
	</ActivePursuitGoal>
	
	<ActivePursuitGoal name="RejectInvitation([target])">
		<PreConditions>
			<Property name="SELF(invitedBy,[target])" operator="=" value="True" />
			<LikeRelation subject="[SELF]" target="[target]" operator="LesserThan" value="0" />
		</PreConditions>
		<SuccessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="rejectinvitation"/>
		</SuccessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Affiliation" target="SELF" value="+2"/>
		</ExpectedEffects>	
	</ActivePursuitGoal>
	

	<ActivePursuitGoal name="RegulateDistress([target])">
		<PreConditions>
			<Property name="[target](isPerson)" operator="=" value="True" />
			<Property name="[target]" operator="!=" value="[SELF]" />
			<LikeRelation subject="[SELF]" target="[target]" operator="GreaterThan" value="0" />
			<EmotionCondition emotion="Distress" agent="[target]" min-intensity="1" />
		</PreConditions>
		<SuccessConditions>
			<!--<NewEvent occurred="True" subject="[target]" action="Smile"/>-->
			<EmotionCondition emotion="JOY" agent="[target]" min-intensity="1" />
		</SuccessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Affiliation" target="[SELF]" value="+3"/>
		</ExpectedEffects>	
	</ActivePursuitGoal>

	<ActivePursuitGoal name="IncreaseRelation([target])">
		<PreConditions>
			<Property name="[target](isPerson)" operator="=" value="True" />
			<Property name="[target]" operator="!=" value="[SELF]" />
			<!--<RecentEvent occurred="True" subject="SELF" action="look-at" target="[target]"/>-->
			<LikeRelation subject="[SELF]" target="[target]" operator="GreaterThan" value="0" />
			<LikeRelation subject="[target]" target="[SELF]" operator="LesserThan" value="2" />
			<!--<EmotionCondition active="False" emotion="JOY" agent="[target]" min-intensity="1" />-->
		</PreConditions>
		<SuccessConditions>
			<!--<NewEvent occurred="True" subject="[target]" action="Smile"/>-->
			<EmotionCondition emotion="JOY" agent="[target]" min-intensity="1" />
		</SuccessConditions>
		<FailureConditions>
		</FailureConditions>			
		<ExpectedEffects>
			<OnSelect drive="Affiliation" target="[SELF]" value="+4"/>
		</ExpectedEffects>	
	</ActivePursuitGoal>
	<ActivePursuitGoal name="DecreaseRelation([target])">
		<PreConditions>
			<Property name="[target](isPerson)" operator="=" value="True" />
			<Property name="[target]" operator="!=" value="[SELF]" />
			<!--<RecentEvent occurred="True" subject="SELF" action="look-at" target="[target]"/>-->
			<LikeRelation subject="[SELF]" target="[target]" operator="LesserThan" value="0" />
			<LikeRelation subject="[target]" target="[SELF]" operator="GreaterThan" value="-2" />
			<EmotionCondition active="False" emotion="DISTRESS" agent="[target]" min-intensity="1" />
		</PreConditions>
		<SuccessConditions>
			<EmotionCondition emotion="DISTRESS" agent="[target]" min-intensity="1" />
		</SuccessConditions>
		<FailureConditions>
		</FailureConditions>			
		<ExpectedEffects>
			<OnSelect drive="Affiliation" target="[SELF]" value="+4"/>
		</ExpectedEffects>	
	</ActivePursuitGoal>
	
	<ActivePursuitGoal name="EmotionSharing([target])">
		<PreConditions>
			<Property name="[target](isPerson)" operator="=" value="True" />
			<Property name="[target]" operator="!=" value="[SELF]" />
			<LikeRelation subject="[SELF]" target="[target]" operator="GreaterThan" value="0" />
			<EmotionalEpisodeCondition episode="[x]" emotion="[e]" value="3" />
			<RecentEvent occurred="False" subject="[SELF]" action="SpeechAct" target="[target]" parameters="episodesummary,[x],[e]"/>
		</PreConditions>
		<SuccessConditions>
			<NewEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="episodesummary,[x],[e]"/>
			<NewEvent occurred="True" subject="[target]" action="SpeechAct" target="[SELF]" parameters="showsupport,[e]"/>
		</SuccessConditions>
		<FailureConditions>
			<NewEvent occurred="True" subject="[target]" action="SpeechAct" target="[SELF]" parameters="rejectsupport"/>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Affiliation" target="[SELF]" value="+4"/>
		</ExpectedEffects>	
	</ActivePursuitGoal>
	<ActivePursuitGoal name="ProvideSupport([target])">
		<PreConditions>
			<Property name="[target](isPerson)" operator="=" value="True" />
			<Property name="[target]" operator="!=" value="[SELF]" />
			<LikeRelation subject="[SELF]" target="[target]" operator="GreaterThan" value="0" />
			<NewEvent occurred="True" subject="[target]" action="SpeechAct" target="[SELF]" parameters="episodesummary,[x],[e]"/>
		</PreConditions>
		<SuccessConditions>
			<NewEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="showsupport,[e]"/>
		</SuccessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Affiliation" target="[target]" value="+4"/>
		</ExpectedEffects>	
	</ActivePursuitGoal>
	<ActivePursuitGoal name="RejectSupport([target])">
		<PreConditions>
			<Property name="[target](isPerson)" operator="=" value="True" />
			<Property name="[target]" operator="!=" value="[SELF]" />
			<LikeRelation subject="[SELF]" target="[target]" operator="LesserThan" value="0" />
			<NewEvent occurred="True" subject="[target]" action="SpeechAct" target="[SELF]" parameters="episodesummary,[x],[e]"/>
		</PreConditions>
		<SuccessConditions>
			<NewEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="rejectsupport"/>
		</SuccessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Affiliation" target="SELF" value="+2"/>
		</ExpectedEffects>	
	</ActivePursuitGoal>	
</GoalLibrary>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/TestGoals.xml
<GoalLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/GoalLibrary.xsd">

	<!-- Interest Goals -->
	
	<ActivePursuitGoal name="Goal1([target])">
		<PreConditions>
			<Property name="[target]" operator="=" value="[SELF]" />
			<Property name="[SELF](isTestMind)" operator="=" value="True" />
			<RecentEvent occurred="False" subject="[SELF]" action="TestAction" target="test" />
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="TestAction" target="test" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
		</ExpectedEffects>		
	</ActivePursuitGoal>
	
	<ActivePursuitGoal name="Goal2([target])">
		<PreConditions>
			<Property name="[SELF](isTestMind)" operator="=" value="True" />
			<Property name="[target](test)" operator="=" value="True" />
			<RecentEvent occurred="False" subject="[SELF]" action="TestAction2" />
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="TestAction2" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
		</ExpectedEffects>		
	</ActivePursuitGoal>
	
</GoalLibrary>
