=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/schemas/GoalLibrary.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:include schemaLocation="Types.xsd" />
<xs:include schemaLocation="Conditions.xsd" />

<xs:element name="GoalLibrary">
  <xs:complexType>
    <xs:sequence>
    	<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="ActivePursuitGoal" type="ActivePursuitGoal" />
    		<xs:element name="InterestGoal" type="InterestGoal"/>
		</xs:choice>
	</xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="ActivePursuitGoal">
    <xs:sequence>
    	<xs:element name="PreConditions" minOccurs="0" maxOccurs="1">
            <xs:complexType>
            	<xs:choice minOccurs="0" maxOccurs="unbounded">
        			<xs:element name="Property" type="PropertyCondition" />
        			<xs:element name="Predicate" type="PredicateCondition" />
        			<xs:element name="RecentEvent" type="EventCondition"/>
        			<xs:element name="PastEvent" type="EventCondition"/>
        			<xs:element name="NewEvent" type="EventCondition"/>
        			<xs:element name="RitualCondition" type="RitualCondition"/>
        			<xs:element name="EmotionCondition" type="EmotionCondition"/>
        			<xs:element name="MoodCondition" type="EmotionCondition"/>
   				</xs:choice>
   			</xs:complexType>
   		</xs:element>	
    	<xs:element name="SucessConditions" minOccurs="0" maxOccurs="1">
            <xs:complexType>
            	<xs:choice minOccurs="0" maxOccurs="unbounded">
        			<xs:element name="Property" type="PropertyCondition" />
        			<xs:element name="Predicate" type="PredicateCondition" />
        			<xs:element name="RecentEvent" type="EventCondition"/>
        			<xs:element name="PastEvent" type="EventCondition"/>
        			<xs:element name="NewEvent" type="EventCondition"/>
        			<xs:element name="EmotionCondition" type="EmotionCondition"/>
        			<xs:element name="MoodCondition" type="MoodCondition"/>
   				</xs:choice>
   			</xs:complexType>
   		</xs:element>	
    	<xs:element name="FailureConditions" minOccurs="0" maxOccurs="1">
            <xs:complexType>
            	<xs:choice minOccurs="0" maxOccurs="unbounded">
        			<xs:element name="Property" type="PropertyCondition" />
        			<xs:element name="Predicate" type="PredicateCondition" />        			
        			<xs:element name="RecentEvent" type="EventCondition"/>
        			<xs:element name="PastEvent" type="EventCondition"/>
        			<xs:element name="NewEvent" type="EventCondition"/>
        			<xs:element name="EmotionCondition" type="EmotionCondition"/>
        			<xs:element name="MoodCondition" type="MoodCondition"/>      			
   				</xs:choice>
   			</xs:complexType>
   		</xs:element>
   		<xs:element name="ExpectedEffects" minOccurs="0" maxOccurs="1">
        		    <xs:complexType>
        		    	<xs:sequence>
					    	<xs:choice minOccurs="0" maxOccurs="unbounded">
								<xs:element name="OnSelect" type="ExpectedEffect" />
    							<xs:element name="OnIgnore" type="ExpectedEffect"/>
							</xs:choice>
        		    	</xs:sequence>
        			</xs:complexType>
        </xs:element>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="InterestGoal">
    <xs:sequence>
    	<xs:element name="ProtectionConstraints" minOccurs="1" maxOccurs="1">
    		<xs:complexType>
				<xs:sequence>
					<xs:element name="Property" type="PropertyCondition" minOccurs="1" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="ExpectedEffect">
 <xs:attribute name="drive" type="externalMotivatorsType" use="required"/>
 <xs:attribute name="target" type="xs:string" use="required"/>
 <xs:attribute name="value" type="xs:string" use="required"/>
</xs:complexType>

</xs:schema>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/ABGoalLibrary.xml
<GoalLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/GoalLibrary.xsd">

	<ActivePursuitGoal name="respondYes([target],[person],[task],[item])">
		<PreConditions>
			<NewEvent occurred="True" subject="[target]" action="ask" target="[SELF]" parameters="[person],[task],[item]" />
			<RecentEvent occurred="True" subject="[person]" action="[task]" target="[item]" />
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[person]" action="[task]" target="[item]" />
			<NewEvent occurred="True" subject="[SELF]" action="respondYes" target="[target]" parameters="[person],[task],[item]" />
		</SucessConditions>
	</ActivePursuitGoal>

	<ActivePursuitGoal name="respondNo([target],[person],[task],[item])">
		<PreConditions>
			<NewEvent occurred="True" subject="[target]" action="ask" target="[SELF]" parameters="[person],[task],[item]" />
			<RecentEvent occurred="False" subject="[person]" action="[task]" target="[item]" />
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="False" subject="[person]" action="[task]" target="[item]" />
			<NewEvent occurred="True" subject="[SELF]" action="respondNo" target="[target]" parameters="[person],[task],[item]" />
		</SucessConditions>
	</ActivePursuitGoal>

</GoalLibrary>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/GoalLibrary-DinnerParty.xml
<GoalLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/GoalLibrary.xsd">

	 <ActivePursuitGoal name="TellJoke([target])">
			<PreConditions>
				<Property name="[SELF](likesToTellJokes)" operator="=" value="True" />
				<Property name="[target](isPerson)" operator="=" value="True" />
				<Property name="[target]" operator="!=" value="[SELF]" />
				<RitualCondition name="GreetingRitual" roles="[SELF],[target]" />		
			</PreConditions>
	
			<SucessConditions>
				<RecentEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="tell-joke" />
			</SucessConditions>
		
			<ExpectedEffects>
				<OnSelect drive="Affiliation" target="[SELF]" value="+3"/>
				<OnSelect drive="Affiliation" target="[target]" value="+3"/>			
			</ExpectedEffects>	
			
		</ActivePursuitGoal>
				
	   <ActivePursuitGoal name="LaughAtJoke([target])">
			<PreConditions>
		      	<RecentEvent occurred="True" subject="[target]" action="SpeechAct" target="[SELF]" parameters="tell-joke" />
			</PreConditions>

			<SucessConditions>
				<RecentEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="laugh-at-joke" />
			</SucessConditions>
				
		    <ExpectedEffects>
			    <OnSelect drive="Affiliation" target="[target]" value="+3"/>			
		    </ExpectedEffects>	
     	</ActivePursuitGoal>
		
		<ActivePursuitGoal name="MockJoke([target])">
			<PreConditions>
	        	<RecentEvent occurred="True" subject="[target]" action="SpeechAct" target="[SELF]" parameters="tell-joke" />
			</PreConditions>

			<SucessConditions>
				<RecentEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="mock-joke" />
			</SucessConditions>
				
		    <ExpectedEffects>
			    <OnSelect drive="Affiliation" target="[SELF]" value="+2"/>	
			    <OnIgnore drive="Affiliation" target="[SELF]" value="-2"/>						
			    <OnSelect drive="Affiliation" target="[target]" value="-4"/>		
		    </ExpectedEffects>	
     	</ActivePursuitGoal>
		
		<ActivePursuitGoal name="AskForMoney([target])">
			<PreConditions>
				<Property name="[SELF](hasMoney)" operator="=" value="False" />
				<Property name="[target](hasMoney)" operator="=" value="True" />
				<RecentEvent occurred="True" subject="[SELF]" action="look-at" target="[target]" />
				<RitualCondition name="GreetingRitual" roles="[SELF],[target]" />
			</PreConditions>
				
			<SucessConditions>
				<RecentEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="ask-for-money" />
			</SucessConditions>
				
		    <ExpectedEffects>
			    <OnSelect drive="Energy" target="[SELF]" value="+4"/>			
		    </ExpectedEffects>	
     	</ActivePursuitGoal>
		
		<ActivePursuitGoal name="GiveMoney([target])">
			<PreConditions>
				<Property name="[SELF](hasMoney)" operator="=" value="True" />
				<Property name="[target]" operator="!=" value="[SELF]" />
				<NewEvent occurred="True" subject="[target]" action="SpeechAct" target="[SELF]" parameters="ask-for-money" />
			</PreConditions>
				
			<SucessConditions>
				<RecentEvent occurred="True" subject="[SELF]" action="give-money" target="[target]"/>
			</SucessConditions>
				
		    <ExpectedEffects>
			    <OnSelect drive="Energy" target="[SELF]" value="-3"/>					
				<OnSelect drive="Energy" target="[target]" value="+4"/>					
				<OnIgnore drive="Energy" target="[target]" value="-4"/>					
		    </ExpectedEffects>	
     	</ActivePursuitGoal>
											
		<ActivePursuitGoal name="GiveAdviceForBetterJob([target])">
			<PreConditions>
				<Property name="[SELF](hasMoney)" operator="=" value="True" />
				<Property name="[target]" operator="!=" value="[SELF]" />
				<NewEvent occurred="True" subject="[target]" action="SpeechAct" target="[SELF]" parameters="ask-for-money" />
			</PreConditions>
				
			<SucessConditions>
				<RecentEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="advice-for-obtaining-money" />
			</SucessConditions>
				
		    <ExpectedEffects>
				<OnSelect drive="Affiliation" target="[SELF]" value="+3"/>					
				<OnIgnore drive="Affiliation" target="[SELF]" value="-3"/>								    
				<OnSelect drive="Energy" target="[target]" value="-3"/>		
				<OnSelect drive="Affiliation" target="[target]" value="-3"/>		
		    </ExpectedEffects>	
     	</ActivePursuitGoal>

		<ActivePursuitGoal name="OfferSmallGift([target])">
			<PreConditions>
				<Property name="[SELF](hasSmallGift)" operator="=" value="True" />
				<Property name="[target](likesGifts)" operator="=" value="True" />
				<Property name="[target](isPerson)" operator="=" value="True" />
				<Property name="[target]" operator="!=" value="[SELF]" />
				<RitualCondition name="GreetingRitual" roles="[SELF],[target]" />		
			</PreConditions>
	
			<SucessConditions>
				<RecentEvent occurred="True" subject="[SELF]" action="give-gift" target="[target]"/>
			</SucessConditions>
		
			<ExpectedEffects>
				<OnSelect drive="Affiliation" target="[SELF]" value="+3"/>
				<OnIgnore drive="Affiliation" target="[SELF]" value="-3"/>
				<OnSelect drive="Affiliation" target="[target]" value="+3"/>			
			</ExpectedEffects>	
			
		</ActivePursuitGoal>
		
		<ActivePursuitGoal name="ExpressGiftContentment([target])">
			<PreConditions>
        <Property name="[SELF](dislikesSmallGifts)" operator="=" value="True" />
        <RecentEvent occurred="True" subject="[target]" action="give-gift" target="[SELF]"/>
      </PreConditions>

      <SucessConditions>
				<RecentEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="show-smallgift-contentment" />
			</SucessConditions>
		
			<ExpectedEffects>
				  <OnSelect drive="Affiliation" target="[target]" value="+3"/>
          <OnIgnore drive="Affiliation" target="[target]" value="-10"/>
      </ExpectedEffects>	

		</ActivePursuitGoal>
		
		
		<ActivePursuitGoal name="ExpressGiftDiscontentment([target])">
			<PreConditions>
				<Property name="[SELF](dislikesSmallGifts)" operator="=" value="True" />
				<RecentEvent occurred="True" subject="[target]" action="give-gift" target="[SELF]"/>
			</PreConditions>
	
			<SucessConditions>
				<RecentEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="show-smallgift-discontentment" />
			</SucessConditions>
		
			<ExpectedEffects>
				<OnSelect drive="Affiliation" target="[SELF]" value="+3"/>	
				<OnIgnore drive="Affiliation" target="[SELF]" value="-10"/>						
				<OnSelect drive="Affiliation" target="[target]" value="-10"/>
			        <OnIgnore drive="Affiliation" target="[target]" value="+10"/>
			</ExpectedEffects>	

		</ActivePursuitGoal>
					
		
		<ActivePursuitGoal name="GoToParty([host])">
			<PreConditions>
				<RecentEvent occurred="True" subject="[SELF]" action="look-at" target="[host]" />
        <Property name="[SELF](place)" operator="!=" value="party-spot" />
				<Property name="[host]" operator="!=" value="[SELF]" />
				<Property name="[host](host)" operator="=" value="True" />
				<Property name="[SELF](hasInvitation)" operator="=" value="True" />
			</PreConditions>	
			
			<SucessConditions>
				<RecentEvent occurred="True" subject="[SELF]" action="walk-to-place" target="party-spot"/>
			</SucessConditions>

			<ExpectedEffects>
				<OnSelect drive="Affiliation" target="[SELF]" value="+10"/>
				<OnSelect drive="Affiliation" target="[target]" value="+10"/>			
				<OnIgnore drive="Affiliation" target="[SELF]" value="-10"/>			
				<OnIgnore drive="Affiliation" target="[target]" value="-10"/>
			</ExpectedEffects>	
		</ActivePursuitGoal>

</GoalLibrary>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/LIRECYr2GoalLibrary.xml
<GoalLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/GoalLibrary.xsd">
	<!-- Getting information from database -->
	<!--ActivePursuitGoal name="ReplyLocation([target])">
		<PreConditions>
			<RecentEvent occurred="True" subject="[target]" action="AskLocation" target="[SELF]" parameters="[agent2]"/>
			<Property name="[agent2](location)" operator="=" value="[location]"/>
			<Property name="[agent2](location)" operator="!=" value="unknown"/>
		</PreConditions>
		<SucessConditions>	
			<RecentEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="replyLocation,[agent2],[location]"/>
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>			
		<ExpectedEffects>
			<OnSelect drive="Affiliation" target="[SELF]" value="+2"/>
			<OnIgnore drive="Affiliation" target="[SELF]" value="-2"/>
		</ExpectedEffects>	
	</ActivePursuitGoal-->
	
	<!-- Getting information through spreading activation -->
	<ActivePursuitGoal name="ReplyLocation([target],[agent2])">
		<PreConditions>
			<RecentEvent occurred="True" subject="[target]" action="AskLocation" target="[SELF]" parameters="[agent2]"/>
		</PreConditions>
		<SucessConditions>	
			<RecentEvent occurred="True" subject="[SELF]" action="SpeechAct" target="[target]" parameters="replyLocation,[agent2],[possibleLocation]"/>
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>			
		<ExpectedEffects>
			<OnSelect drive="Affiliation" target="[SELF]" value="+2"/>
			<OnIgnore drive="Affiliation" target="[SELF]" value="-2"/>
		</ExpectedEffects>	
	</ActivePursuitGoal>
	
</GoalLibrary>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/CICESEGoalLibrary.xml
<GoalLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/GoalLibrary.xsd">
	
	<!-- Bienvenida -->
	<ActivePursuitGoal name="SaludoBienvenida([AGENT])">
		<PreConditions>
			<RecentEvent subject="[AGENT]" action="Inicia_Sesion"/>
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="Bienvenida" target="[AGENT]"/>
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
	</ActivePursuitGoal>

	<!-- MostrarInteres -->
	<ActivePursuitGoal name="MostrarInteres([AGENT])">
		<PreConditions>
			<RecentEvent subject="[AGENT]" action="Responde_Bienvenida"/>
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="Interesarse" target="[AGENT]"/>
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
	</ActivePursuitGoal>

	<!-- Disculpas -->
	<ActivePursuitGoal name="AceptaDisculpas([AGENT])">
		<PreConditions>
			<RecentEvent subject="[AGENT]" action="Ofrece_Disculpa" target="[SELF]"/>
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="DisculpaAceptada" target="[AGENT]"/>
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
	</ActivePursuitGoal>

	<!-- Saludo -->
	<ActivePursuitGoal name="RespondeSaludo([AGENT])">
		<PreConditions>
			<RecentEvent subject="[AGENT]" action="Saluda"/>
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="Saludar" target="[AGENT]"/>
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
	</ActivePursuitGoal>

	<!-- Felicitar -->
	<ActivePursuitGoal name="Felicita_Logro([AGENT])">
		<PreConditions>
			<RecentEvent subject="[AGENT]" action="Informa_Ascenso"/>
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="Felicita" target="[AGENT]"/>
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
	</ActivePursuitGoal>


	<!-- Mostrar Preocupacion -->
	<ActivePursuitGoal name="MostrarPreocupacion([AGENT])">
		<PreConditions>
			<RecentEvent subject="[AGENT]" action="Informa_Traslado"/>
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="ExpresarPreocupacion" target="[AGENT]"/>
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
	</ActivePursuitGoal>
			
</GoalLibrary>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/SimpleGoalLibrary.xml
<GoalLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/GoalLibrary.xsd">
	<ActivePursuitGoal name="Eat([target])">
		<PreConditions>
			<Property name="[target](eatable)" operator="=" value="True" />
			<Property name="[target](onfloor)" operator="=" value="True" />	
		</PreConditions>
		<SucessConditions>
			<NewEvent occurred="True" subject="SELF" action="Eat" target="[target]" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>	
	</ActivePursuitGoal>
	<ActivePursuitGoal name="TellWrong(User)">
		<PreConditions>
			<Property name="badsequence()" operator="=" value="True" />
			<NewEvent occurred="True" subject="User" action="SelectNote" target="[x]" />	
		</PreConditions>
		<SucessConditions>
			<NewEvent occurred="True" subject="SELF" action="TellWrong" target="User" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>	
	</ActivePursuitGoal>
	<ActivePursuitGoal name="Congratulate(User)">
		<PreConditions>
			<Property name="goodsequence()" operator="=" value="True" />
			<NewEvent occurred="True" subject="User" action="SelectNote" target="[x]" />	
		</PreConditions>
		<SucessConditions>
			<NewEvent occurred="True" subject="SELF" action="Congratulate" target="User" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>	
	</ActivePursuitGoal>
	
	<ActivePursuitGoal name="CongratulateForDuration(User)">
		<PreConditions>
			<Property name="goodDurationSequence()" operator="=" value="True" />
			<NewEvent occurred="True" subject="User" action="SelectDuration" target="[x]" />	
		</PreConditions>
		<SucessConditions>
			<NewEvent occurred="True" subject="SELF" action="Congratulate" target="User" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>	
	</ActivePursuitGoal>
	<ActivePursuitGoal name="TellWrongDuration(User)">
		<PreConditions>
			<Property name="badDurationSequence()" operator="=" value="True" />
			<NewEvent occurred="True" subject="User" action="SelectDuration" target="[x]" />	
		</PreConditions>
		<SucessConditions>
			<NewEvent occurred="True" subject="SELF" action="TellWrong" target="User" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>	
	</ActivePursuitGoal>
</GoalLibrary>

=== karenreyesgas/Java/FAtiMA-ModularP/data/characters/minds/GoalLibrary-TeamBuddy.xml
<GoalLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./schemas/GoalLibrary.xsd">

	<!-- Interest Goals -->
	
	<ActivePursuitGoal name="MorningGreeting([target])">
		<PreConditions>
			<Property name="[target](isPerson)" operator="=" value="True" />
			<RecentEvent occurred="False" subject="[SELF]" action="Spact" target="[target]" parameters="greet" />
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="Spact" target="[target]"  parameters="greet" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Energy" target="[SELF]" value="-1"/>
			<OnSelect drive="Affiliation" target="[SELF]" value="+3"/>
			<OnIgnore drive="Affiliation" target="[SELF]" value="-3"/>
		</ExpectedEffects>		
	</ActivePursuitGoal>
	
	<ActivePursuitGoal name="DeliverPhone([target])">
		<PreConditions>
			<Property name="[target](isPerson)" operator="=" value="True" />
			<Property name="Phone(isRinging)" operator="=" value="True" />
			<Property name="Phone(onRobot)" operator="=" value="True" />
		</PreConditions>
		<SucessConditions>
			<Property name="Phone(onRobot)" operator="=" value="False" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Energy" target="[SELF]" value="-1"/>
			<OnSelect drive="Affiliation" target="[SELF]" value="+3"/>
			<OnIgnore drive="Affiliation" target="[SELF]" value="-3"/>
		</ExpectedEffects>		
	</ActivePursuitGoal>
	
	<ActivePursuitGoal name="Remind([target],[reminder])">
		<PreConditions>
			<Property name="[reminder](isReminder)" operator="=" value="True" />
			<Property name="[target](isPerson)" operator="=" value="True" />
			<Property name="[reminder](for,[target])" operator="=" value="True" />
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="Spact" target="[target]" parameters="remind,[reminder]" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Energy" target="[SELF]" value="-1"/>
			<OnSelect drive="Affiliation" target="[SELF]" value="+3"/>
			<OnIgnore drive="Affiliation" target="[SELF]" value="-3"/>
		</ExpectedEffects>		
	</ActivePursuitGoal>
	
	<ActivePursuitGoal name="ChargeAt([charger])">
		<PreConditions>
			<Property name="[charger](isChargingStation)" operator="=" value="True" />
			<NewEvent occurred="False" subject="[SELF]" action="Charge" target="[charger]" />
		</PreConditions>
		<SucessConditions>
			<NewEvent occurred="True" subject="[SELF]" action="Charge" target="[charger]" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Energy" target="[SELF]" value="+8.5"/>
			<OnSelect drive="Affiliation" target="[SELF]" value="-5"/>
		</ExpectedEffects>		
	</ActivePursuitGoal>
	
	<ActivePursuitGoal name="Migration([platform])">
		<PreConditions>
			<Property name="[platform](isMigrationTarget)" operator="=" value="True" />
			<RecentEvent occurred="False" subject="[SELF]" action="Migrate" target="[platform]" />
		</PreConditions>
		<SucessConditions>
			<RecentEvent occurred="True" subject="[SELF]" action="Migrate" target="[platform]" />
		</SucessConditions>
		<FailureConditions>
		</FailureConditions>
		<ExpectedEffects>
			<OnSelect drive="Energy" target="[SELF]" value="+5"/>
			<OnIgnore drive="Energy" target="[SELF]" value="-5"/>
		</ExpectedEffects>		
	</ActivePursuitGoal>
		
</GoalLibrary>
